<?php

/**
 * @file
 *   Install and related hooks for apachesolr_search.
 */

/**
 * Implements hook_enable().
 * Set DEV Discovery as default search enviorment
 */
function dlts_solr_enable() {
  db_update('apachesolr_environment')->fields(array('env_id' => 'solr', 'name' => 'Discovery Apache Solr 6.x server', 'url' => 'http://stagediscovery.dlib.nyu.edu:8080/solr3_discovery/viewer'))->execute();
}
